/**
 * Default chunk size used when the caller does not provide a custom value.
 */
const DEFAULT_CHUNK_SIZE = 5 * 1024 * 1024;

/**
 * Public status exposed by the current coordinator instance.
 */
export type FileCoordinatorStatus =
  | 'INIT'
  | 'PREPARING'
  | 'READY'
  | 'UPLOADING'
  | 'PAUSED'
  | 'COMPLETING'
  | 'COMPLETED'
  | 'CANCELED'
  | 'ERROR';

/**
 * Stable identity string derived from the current file metadata.
 */
export type FileCoordinatorFileIdentity = string;

/**
 * Public configuration accepted by a single `FileCoordinator` instance.
 */
export interface FileCoordinatorOptions {
  /**
   * Chunk size in bytes used to split the current file.
   */
  chunkSize?: number;
}

/**
 * Lightweight summary returned after one preparation pass completes.
 */
export interface FileCoordinatorPrepareResult {
  /**
   * Stable identity of the current file.
   */
  fileIdentity: FileCoordinatorFileIdentity;
  /**
   * Runtime status captured after the current preparation pass.
   */
  status: FileCoordinatorStatus;
  /**
   * Total chunk count generated by the current preparation pass.
   */
  chunkCount: number;
  /**
   * Effective chunk size used by the current preparation pass.
   */
  chunkSize: number;
}

/**
 * Internal descriptor used to represent one file chunk.
 */
interface FileCoordinatorChunk {
  /**
   * Zero-based chunk index.
   */
  index: number;
  /**
   * Inclusive start byte offset of the chunk.
   */
  start: number;
  /**
   * Exclusive end byte offset of the chunk.
   */
  end: number;
  /**
   * Byte length of the chunk.
   */
  size: number;
}

/**
 * Coordinates one file instance and prepares internal chunk metadata for later upload steps.
 */
export class FileCoordinator {
  /**
   * Original file selected by the caller.
   */
  private readonly file: File;
  /**
   * Stable identity generated for the current file.
   */
  private readonly fileIdentity: FileCoordinatorFileIdentity;
  /**
   * Normalized options stored for the current coordinator instance.
   */
  private readonly options: FileCoordinatorOptions;
  /**
   * Internal chunk list used by later upload scheduling logic.
   */
  private chunks: FileCoordinatorChunk[];
  /**
   * Active preparation task reused by concurrent `prepare()` calls.
   */
  private preparePromise: Promise<FileCoordinatorPrepareResult> | null = null;
  /**
   * Latest successful preparation summary of the current file.
   */
  private prepareResult: FileCoordinatorPrepareResult | null = null;
  /**
   * Current runtime status of the coordinator.
   */
  private status!: FileCoordinatorStatus;

  /**
   * Creates a coordinator bound to one selected file.
   *
   * @param file File selected by the user.
   * @param options Runtime configuration for the current file.
   */
  constructor(
    file: File,
    options: FileCoordinatorOptions = {},
  ) {
    this.file = file;
    this.fileIdentity = this.createFileIdentity();
    this.options = {
      ...options,
      chunkSize: Math.max(1, options.chunkSize ?? DEFAULT_CHUNK_SIZE),
    };
    this.chunks = [];
    this.setStatus('INIT');
  }

  /**
   * Returns the original `File` instance bound to the coordinator.
   */
  getFile() {
    return this.file;
  }

  /**
   * Returns the stable identity string of the current file.
   */
  getFileIdentity() {
    return this.fileIdentity;
  }

  /**
   * Returns the normalized runtime options of the current coordinator.
   */
  getOptions() {
    return { ...this.options };
  }

  /**
   * Returns the current runtime status of the coordinator.
   */
  getStatus() {
    return this.status;
  }

  /**
   * Runs the first-stage preparation flow for the current file.
   *
   * Repeated calls are safe. When a preparation task is already running,
   * later callers reuse the same promise instead of starting a new run.
   *
   * Returns a lightweight summary of the prepared file metadata.
   */
  async prepare() {
    if (this.preparePromise) {
      return this.preparePromise;
    }

    const prepareTask = (async () => {
      this.setStatus('PREPARING');
      this.prepareResult = null;
      this.resetChunks();
      this.chunks = this.createChunks();
      this.setStatus('READY');
      this.prepareResult = this.createPrepareResult();
      return this.prepareResult;
    })();

    const wrappedPrepareTask = prepareTask.finally(() => {
      if (this.preparePromise === wrappedPrepareTask) {
        this.preparePromise = null;
      }
    });

    this.preparePromise = wrappedPrepareTask;
    return wrappedPrepareTask;
  }

  /**
   * Returns the total number of chunks generated for the current file.
   */
  getChunkCount() {
    return this.chunks.length;
  }

  /**
   * Returns the latest successful preparation summary.
   */
  getPrepareResult() {
    if (!this.prepareResult) {
      return null;
    }

    return { ...this.prepareResult };
  }

  /**
   * Updates the internal runtime status of the coordinator.
   */
  private setStatus(status: FileCoordinatorStatus) {
    this.status = status;
  }

  /**
   * Clears the previously prepared chunk metadata before rebuilding it.
   */
  private resetChunks() {
    this.chunks = [];
  }

  /**
   * Creates the public summary object returned by `prepare()`.
   */
  private createPrepareResult(): FileCoordinatorPrepareResult {
    return {
      fileIdentity: this.fileIdentity,
      status: this.status,
      chunkCount: this.chunks.length,
      chunkSize: this.options.chunkSize ?? DEFAULT_CHUNK_SIZE,
    };
  }

  /**
   * Creates a stable identity string for the current file.
   */
  private createFileIdentity(): FileCoordinatorFileIdentity {
    return `${this.file.name}__${this.file.size}__${this.file.lastModified}`;
  }

  /**
   * Splits the current file into deterministic chunks based on `chunkSize`.
   */
  private createChunks(): FileCoordinatorChunk[] {
    const chunkSize = this.options.chunkSize ?? DEFAULT_CHUNK_SIZE;

    if (this.file.size === 0) {
      return [];
    }

    const chunks: FileCoordinatorChunk[] = [];
    let start = 0;
    let index = 0;

    while (start < this.file.size) {
      const end = Math.min(start + chunkSize, this.file.size);

      chunks.push({
        index,
        start,
        end,
        size: end - start,
      });

      start = end;
      index += 1;
    }

    return chunks;
  }
}
